<?php

return [
    'title'       => 'LIIF Annual Report 2024',
    'description' => 'Website description goes here.',
    'staging'     => false,
    'baseUrl'     => 'https://liif-annual-report-2024.test',
    'social'      => [
        'linkedin' => 'https://www.linkedin.com/company/low-income-investment-fund/',
        'facebook' => 'https://www.facebook.com/liifund/',
        'x'        => 'https://x.com/Liifund',
        'youtube'  => 'https://www.youtube.com/user/LIIFund',
    ],
    'collections' => [
        'officers' => [
            'items' => [
                [
                    'name'  => 'John Doe',
                    'title' => 'Chairman',
                ],
                [
                    'name'  => 'Jane Doe',
                    'title' => 'Vice Chairman',
                ],
            ],
        ],
        'directors' => [
            'items' => [
                [
                    'name'  => 'John Doe',
                    'title' => 'Chairman',
                ],
                [
                    'name'  => 'Jane Doe',
                    'title' => 'Vice Chairman',
                ],
            ],
        ],
        'senior_staff' => [
            'items' => [
                [
                    'name'  => 'John Doe',
                    'title' => 'Chairman',
                ],
                [
                    'name'  => 'Jane Doe',
                    'title' => 'Vice Chairman',
                ],
            ],
        ],
        'supporters' => [
            'items' => [
                '609 Broad Street',
                'Alphadyne Asset Management',
                'Amalgamated Bank',
                'Annie E. Casey Foundation',
                'Arnold Ventures',
                'Ballmer Group',
                'Bank of America Charitable Foundation',
                'Bay Area Metropolitan Transportation Commission',
                'California Department of Housing and Community Development',
                'Calvert Impact Capital',
                'Capital One',
                'Cathay Bank Foundation',
                'Charles Schwab Bank',
                'City and County of San Francisco',
                'City First Bank',
                'Community Foundation for Greater Atlanta',
                'Community Investment Guarantee Pool',
                'CTBC Bank',
                'D.C. Dept. of Housing and Community Development',
                'D.C. Office of the State Superintendent of Education',
                'Deutsche Bank Trust Company Americas',
                'Erich and Hannah Sachs Foundation',
                'Federal Home Loan Bank of San Francisco',
                'First Citizens Bank',
                'First Five Riverside',
                'Ford Foundation',
                'Goldman Sachs',
                'Goldman Sachs Foundation',
                'Georgia Power Foundation',
                'Heising-Simons Foundation',
                'Housing Partnership Network',
                'HSBC Bank USA, N.A.',
                'Invest Atlanta',
                'JPB Foundation',
                'JPMorgan Chase &amp; Co.',
                'JPMorgan Chase Foundation',
                'Kalliopeia Foundation',
                'Kresge Foundation',
                'Lift to Rise',
                'Los Angeles County Metropolitan Transportation Authority',
                'Manufacturers Bank',
                'Marisla Foundation',
                'Massachusetts Housing Investment Corporation',
                'Mercy Investment Services, Inc.',
                'Metropolitan Transportation Commission',
                'Mizuho Bank (USA)',
                'Morgan Stanley',
                'MUFG Union Bank',
                'National Affordable Housing Trust',
                'National Children’s Facilities Network',
                'National Resources Defense Council',
                'New York City Acquisition Fund',
                'New York City Housing Development Corporation',
                'New York Community Trust',
                'Northern Trust',
                'NY Quarterly Meeting of the Religious Society of Friends',
                'PNC Bank',
                'Purpose Built Communities',
                'Prudential Financial',
                'Robert Wood Johnson Foundation',
                'San Francisco Friends School',
                'Santander Bank',
                'Satterberg Foundation',
                'Self-Help Federal Credit Union',
                'Sisters of Charity of the Incarnate Word',
                'Trillium Asset Management',
                'Trinity Health Corporation',
                'Truist Bank',
                'Truist Foundation',
                'UMC Benefit Board',
                'U.S. Bank National Association',
                'U.S. Department of the Treasury CDFI Fund',
                'Wells Fargo Bank',
                'Wells Fargo Foundation',
            ],
        ],
    ],
];
